# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [1]:
import numpy as np
print(np.zeros((2, 3)))
print(np.empty((2, 3)))

'''
np.zero本身是具備一個值，只是那個值是0，而np.empty則不具備任何值，而需要設計者去設計值進去
'''

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [35]:
# 記得先 Import 正確的套件

import numpy as np
a = np.random.rand(2, 3)
b=a*100

print(b)
print(b.round())
print(np.round(b))


[[ 4.40462288 86.08876291  9.67928653]
 [53.00852845 23.89114841 45.10903167]]
[[ 4. 86. 10.]
 [53. 24. 45.]]
[[ 4. 86. 10.]
 [53. 24. 45.]]


In [47]:
# 參考解答

a = np.random.rand(2, 3)

b=a*100

print(b)
print(b.round())
print(np.round(b))

[[95.56224785 20.73133047 86.92417277]
 [ 4.11935652 40.68415711 36.97533209]]
[[96. 21. 87.]
 [ 4. 41. 37.]]
[[96. 21. 87.]
 [ 4. 41. 37.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [46]:
import numpy as np

a = np.random.rand(2, 3)
m = 20
n = 40
b=a*(n-m)
c=b%1
d=(b-b%1)+m
print(a)
print(b)
print(c)
print(d)


[[0.26729866 0.5535142  0.06512831]
 [0.84233153 0.45427004 0.45639216]]
[[ 5.34597314 11.0702841   1.30256617]
 [16.84663067  9.08540088  9.12784312]]
[[0.34597314 0.0702841  0.30256617]
 [0.84663067 0.08540088 0.12784312]]
[[25. 31. 21.]
 [36. 29. 29.]]


'\nYour Code\n'